### PR TITLE
Update to Worldguard 7 beta 3

### PR DESCRIPTION
**Pull request by wizjany**
*Remove jars in favor of maven.

*Drop dependence on WorldGuard plugin - use the core API.

*Fix for API changes in beta 3.

Note that I also added a travis yml to test builds. This won't do anything unless the repo owner enables builds on travis-ci.com
Also just a warning, this isn't tested. It compiles though.

### CODE REVIEW

**Comment by MrSpock78** [comment]
`[20:42:17 WARN]: [Dynmap-WorldGuard] Task #73 for Dynmap-WorldGuard v1.1-SNAPSHOT generated an exception
java.lang.NoSuchMethodError: com.sk89q.worldguard.WorldGuard.getProfileCache()Lcom/sk89q/squirrelid/cache/ProfileCache;
        at org.dynmap.worldguard.DynmapWorldGuardPlugin.formatInfoWindow(DynmapWorldGuardPlugin.java:116) ~[?:?]
        at org.dynmap.worldguard.DynmapWorldGuardPlugin.handleRegion(DynmapWorldGuardPlugin.java:284) ~[?:?]
        at org.dynmap.worldguard.DynmapWorldGuardPlugin.access$100(DynmapWorldGuardPlugin.java:45) ~[?:?]
        at org.dynmap.worldguard.DynmapWorldGuardPlugin$UpdateJob.run(DynmapWorldGuardPlugin.java:350) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-509]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-509]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-509]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-509]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-509]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-509]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]`
I get this exception with this build. 
That fork is working fine: https://github.com/kaiarne/Dynmap-WorldGuard

**Comment by wizjany** [comment]
ah yea that's kind of a problem. the profile cache isn't supposed to be public API really, and it's relocated to an internal package in the distributed plugin. and we don't publish that because it's not meant to be built on. hmm.

**Comment by mikeprimm** [comment]
Appreciate the changes - I'll be altering it a bit more, as I don't like being dependent on SNAPSHOT builds (since they can change without being relevant to what folks who are running the releases are using, and I really cannot meaningfully say what supporting '7.0.0-SNAPSHOT' means from week to week).

**Comment by wizjany** [comment]
We don't have release/beta builds published to our maven because that might imply some stability.
I think right now the issue is less about changes between builds, and more about the use of public methods that weren't meant to be public API (i.e. ProfileCache). Since the entire squirrelID package is relocated in our release builds, there's binary incompatibility for anything that builds on our maven artifacts but runs on -dist jars. Perhaps this is why it was necessary to manually provide built jars.

I discussed with Me4502 the possibility of abstracting the profile system so that it doesn't require external users of the API to build on internal squirrelid classes, so we will probably change something there again soon.

**Comment by mikeprimm** [comment]
Cool - I'll be happy to work with whatever you guys think is best: key thing for me is that I support specific releases, and don't want to have problems with myself (or other folks) trying to do a fix or enhancement and winding up with an update that only works for folks running your daily snapshots vs being an update that still works on the last formal release.  I'd love to have a 'blessed' way to do what is needed for this plugin, and will definitely defer to whatever interfaces you and your team advise - we could marry the updating of this plugin to your release schedule, in which case the snapshot concern would be reduced: I'd just need to be kept in the loop on your formal release plans so that we can minimize breaks (and I might just pin the library version to your specific build JUST for the release build, and then 'float' it when I slide back to SNAPSHOT myself....).  Anyway, definitely willing to work to get the best results for everyone involved.

**Comment by wizjany** [comment]
pending https://github.com/EngineHub/WorldGuard/pull/394, this will work just by recompiling on the new snapshot.

**Comment by wizjany** [comment]
download the source and run `mvn package`.

**Comment by Sikatsu** [comment]
The dynmap worldguard source? I'm not familiar with this.

**Pull request merged**
